### PR TITLE
issue #650 fix proposal

### PR DESCRIPTION
**Pull request by Matioupi**
Modified hackrf_stop_tx and hackrf_stop_rx to first join the transfer thread before setting the receiver to OFF mode (cf. issue #650)

### CODE REVIEW

**Comment by Matioupi** [comment]
Only the first commit of this PR is actually related to #650, but as I suck at using git/github properly, the other commits I have made in my fork (about adding a python wrapper to libhackrf) also ended up here.

**Comment by Matioupi** [comment]
The other changes than 2a089c3 may also be interesting ( python binding for libhackrf, also it's not related to related to #650 ).

**Comment by mossmann** [comment]
The Python stuff is very interesting!  However, we are likely to migrate the entire HackRF software onto the GreatFET codebase which will result in a different method of access from Python.

**Comment by mossmann** [comment]
I've merged just 2a089c3.  The other stuff should be considered separately.

**Pull request closed without merging**
