### PR TITLE
Multi device hardware sync

### PR DESCRIPTION
**Pull request by dodgymike**
Multi device hardware sync

### CODE REVIEW

**Comment by mossmann** [comment]
What is the purpose of usb_dummy_buffer?  It looks like a big waste of RAM.

**Comment by dodgymike** [comment]
Sorry that was an early attempt at pushing known data through to the host so I could filter it out. Should've been removed ages ago.

**Comment by mossmann** [comment]
Cool.  That's what we figured.  Everything else looks good.

**Comment by mossmann** [comment]
I merged it, but it was tricky. Can you test to make sure the hw_sync mode still works?

**Pull request merged**
