### PR TITLE
Update HackRF readme

### PR DESCRIPTION
**Pull request by straithe**

### CODE REVIEW

**Review by epenelope — CHANGES_REQUESTED** [review]
Minor correction for subject-verb agreement please: 'your _question_ is' or 'your questions _are_'.

**Review by epenelope — COMMENTED** [review]
Is there a more specific sphinx-doc link we could provide, perhaps with build instructions?

**Comment by straithe** [comment]
Thank you, @epenelope. Ready for another review!

**Comment by straithe** [comment]
> Minor correction for subject-verb agreement please: 'your _question_ is' or 'your questions _are_'.

Done! Thank you.

**Review by epenelope — APPROVED** [review]
Perfect, @straithe! Thank you!

**Pull request merged**
