### PR TITLE
Receive streaming implementation

### PR DESCRIPTION
**Pull request by Sec42**
This adds a -S option to hackrf_transfer to enable receive streaming with a circular buffer of the specified size.

This makes it possible to stream data to processes which might block for short amounts of time while reading data, without loosing data. It also gives clean notifications if data is lost and never automatically exits even if the output is blocked for some time.

This is very useful when piping the output of hackrf_transfer to another process on a CPU-starved machine.

### CODE REVIEW

**Comment by Sec42** [comment]
@mossmann The Travis build failure is because it uses (old) gcc 4.6.3 - gcc >=4.7.0 follows the C11 standard with regard to atomic operations, and compiles fine.

**Comment by dominicgs** [comment]
While I agree that gcc 4.7.0 is old enough that we could rely on it for Linux users, I am unsure how Clang supports `atomic_*` and we also have a reasonable number of people using libhackrf on Windows hosts as compiled by msvc (which I believe has terrible C11 support).

**Comment by schneider42** [comment]
It's green now ;)

**Comment by schneider42** [comment]
I don't have Windows (TM) machine at hand to see if it compiles there. The code only gets executed if you specify the parameter.

**Comment by mossmann** [comment]
Thank you for your contribution!

**Pull request merged**
