### PR TITLE
Don't re-init bulk endpoints on every set_transceiver_mode call

### LINKED ISSUE #368: Looping in one-shot mode causes hackrf_sweep to fail
### Steps to reproduce
1. while true; do /usr/local/bin/hackrf_sweep -f100:140 -w 5000 -l 32 -g 8 -1; sleep 5; done

### Expected behaviour
Power levels for each frequency in the spectrum interval given on the command line

### Actual behaviour
Runs fine for awhile, then:
13.4 MiB / 1.000 sec = 13.4 MiB/second
13.4 MiB / 1.000 sec = 13.4 MiB/second
13.4 MiB / 1.000 sec = 13.4 MiB/second
13.4 MiB / 1.000 sec = 13.4 MiB/second
13.4 MiB / 1.000 sec = 13.4 MiB/second
13.4 MiB / 1.000 sec = 13.4 MiB/second
.........
May resume normal operation after awhile.

### Version information
**Operating system**: CentOS 7

**hackrf_info output:**
Found HackRF board 0:
USB descriptor string: 0000000000000000a06063c82365215f
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1
Part ID Number: 0xa000cb3c 0x005d4f4b
Serial Number: 0x00000000 0x00000000 0xa06063c8 0x2365215f

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

### PR DESCRIPTION
**Pull request by miek**
Fixes #368

### CODE REVIEW

**Comment by mossmann** [comment]
Can you please also remove the calls to usb_endpoint_init() from usb_vendor_request_set_transceiver_mode() and main()?

**Comment by miek** [comment]
I've removed that call from usb_vendor_request_set_transceiver_mode() and checked that `hackrf_cpldjtag` still works correctly. I left the ones in main() as they're for the control endpoints, not the bulk ones.

**Comment by ktemkin** [comment]
These look correct to me; though I haven't tested on hardware.

**Comment by mossmann** [comment]
Ah, I missed that the ones in main() were for the control endpoint.  Thank you!

**Pull request merged**
