### PR TITLE
Add support for transmitting/receiving from stdin/stdout

### PR DESCRIPTION
**Pull request by rgerganov**
When '-' is used for filename, write samples to stdout when receiving or
read samples from stdin when transmitting. This allows using
hackrf_transfer in shell pipes with tools like csdr.
User info messages are written to stderr.

### CODE REVIEW

**Comment by rxseger** [comment]
👍 Great enhancement, I was trying to do this as well but specifying /dev/stdout as a workaround failed since log messages were interleaved, your changes to use stderr for logging works beautifully. 

With stdout/stdin support in hackrf_transfer, I can do this:

hackrf_transfer -r - -f 1090000000 -s 2000000 -p 0 -a 0 -l 40 -g 62 | sox --rate 2000000 --channels 1 --type sb - --type ub - | ./dump1090 --ifile -

using [dump1090-mutability](https://github.com/mutability/dump1090) (even though it only officially supports RTL-SDR, using unsigned samples) and [sox](http://sox.sourceforge.net) to receive and decode live ADS-B transmissions.

**Comment by dominicgs** [comment]
This looks good, I hope to merge it, along with other outstanding PRs, when I get time for more HackRF development in a week or two.

@rxseger While I understand that usefulness of this PR, in your case you can also use this version of dump1090: https://github.com/itemir/dump1090_sdrplus which has built in support for HackRF.

**Comment by ckuethe** [comment]
I've been meaning to try add osmosdr to sdrplus tree so it'll just work with everything. Not enough "round tuits" yet though...

**Comment by theforcedk** [comment]
@dominicgs How does https://github.com/itemir/dump1090_sdrplus have support for HackRF? All it does, is specify that you should use hackrf_transfer to generate a file, which you then read into dump1090 using "ifile".. please enlighten. Is the support through sdrplus? I do not see any HackRF code in the repo.

@rxseger I got it working fine without this pull request tho; been using this for a while now.

screen shot 2016-06-09 at 16 40 36

hackrf_1090_rx.sh:

`#!/bin/sh
FREQUENCY=1090000000
SAMPLE_RATE=2000000
AMPLIFIER=1
LNA_AMPLIFIER=37
BASEBAND_GAIN=47

# move to dump1090 folder in order to avoid "Error opening HTML file: No such file or directory"
cd /Users/yoda/Development/Source/dump1090/

# best
hackrf_transfer -r /dev/stdout -f $FREQUENCY -s $SAMPLE_RATE -p 0 -a $AMPLIFIER -l $LNA_AMPLIFIER -g $BASEBAND_GAIN |

# sox converts 8 bit signed iq samples to unsigned
sox -r $SAMPLE_RATE -c 1 -t sb - -t ub - |

# dump1090 processes the raw unsigned output from sox
/Users/yoda/Development/Source/dump1090/dump1090 "$@" --metric --fix --aggressive --net --net-http-port 1337 --ifile -
`

**Pull request merged**
