### PR TITLE
Portapack and rad1o UI restructuring

### PR DESCRIPTION
**Pull request by dominicgs**
This supersedes #586 by adding a commit for rad1o badge.

This builds and runs on rad1o badge as a standalone firmware. 

I cannot get this to build as part of the hackrfapp in the larger rad1o firmware.  However, I believe that compatibility has been broken for a while now and is not part of this change.

### CODE REVIEW

**Comment by schneider42** [comment]
Thanks!

**Comment by jboone** [comment]
@dominicgs I may have just addressed the same issue you did in 
e4fae35, in my jboone/ui_restructuring branch commit 4fefd8. I've probably made a mess of the commit tree in the process. Sorry...

**Comment by jboone** [comment]
@dominicgs Fixing this. I'm cherry-picking your last commit and mushing it together with mine. I'll submit a new pull request shortly.

**Comment by dominicgs** [comment]
Closing as this is superseded by #602

**Pull request closed without merging**
