### PR TITLE
Update hackrf_sweep.c

### PR DESCRIPTION
**Pull request by ggatis**
change if ( fd != NULL ) to if ( ( fd != NULL ) && ( fd != stdout ) )
before fclose( fd );

### CODE REVIEW

**Comment by miek** [comment]
Is there a problem with calling `fclose` on `stdout`? As far as I'm aware there isn't any issue with it and it's sometimes recommended, to ensure that any output is flushed before exiting.

**Comment by ggatis** [comment]
Hi!
 
stdout is provided by OS and IMHO it should be managed by OS even if there
are no issuses.
Actually I lost print operator functionality in python when sweep finished
after calling it as dll.

Kind regards ~

Gatis

 


  _____

**Comment by mossmann** [comment]
I'm going to accept this patch because it seems that the potential consequences of closing stdout are slightly worse than the potential consequences of not closing stdout, but we do suggest using `dup()` if you are doing things like dynamically linking another program's `main()` into your own.

**Comment by mossmann** [comment]
Thank you for your contribution!

**Comment by ggatis** [comment]
OK! Thank you for pointing to dup()!

Kind regards ~
Gatis

**Comment by ggatis** [comment]
You’re welcome!

**Pull request merged**
